config/routes.rb
Rails.application.routes.draw do


  #resources :organization_permissions
  resources :organizations do
    resources :properties do
      resources :bookings
    end

    resources :permissions

  end
  
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
  devise_for :users, :path  => '/users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=end
  #devise_scope :user do
  #   get   '/users/sign_in'  => 'users/sessions#new',  as: :new_user_session
  #end
  devise_for :users, path: "", controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmation: "users/confirmations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}


  resources :users

  root "static_pages#about"
  match 'about_us', to: 'static_pages#about', via: :get
  match 'team', to: 'static_pages#team', via: :get
  match 'contact_us', to: 'static_pages#contact_us', via: :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  #match '404', to:  redirect('/')

  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, :via => :all
end

app/models/organization_permission.rb
class OrganizationPermission < ApplicationRecord
  belongs_to :organization
  belongs_to :user

end

app/controllers/organization_permissions_controller.rb
class OrganizationPermissionsController < ApplicationController
  before_action :set_organization_permission, only: [:show, :edit, :update, :destroy]

  # GET /organization_permissions
  # GET /organization_permissions.json
  def index
    @organization= Organization.find(params[:organization_id]).users
  end

  # GET /organization_permissions/1
  # GET /organization_permissions/1.json
  def show
  end

  # GET /organization_permissions/new
  def new
    @organization_permission = OrganizationPermission.new
  end

  # GET /organization_permissions/1/edit
  def edit
  end

  # POST /organization_permissions
  # POST /organization_permissions.json
  def create
    @organization_permission = OrganizationPermission.new(organization_permission_params)

    respond_to do |format|
      if @organization_permission.save
        format.html { redirect_to @organization_permission, notice: 'Organization permission was successfully created.' }
        format.json { render :show, status: :created, location: @organization_permission }
      else
        format.html { render :new }
        format.json { render json: @organization_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organization_permissions/1
  # PATCH/PUT /organization_permissions/1.json
  def update
    respond_to do |format|
      if @organization_permission.update(organization_permission_params)
        format.html { redirect_to @organization_permission, notice: 'Organization permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization_permission }
      else
        format.html { render :edit }
        format.json { render json: @organization_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organization_permissions/1
  # DELETE /organization_permissions/1.json
  def destroy
    @organization_permission.destroy
    respond_to do |format|
      format.html { redirect_to organization_permissions_url, notice: 'Organization permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization_permission
      @organization_permission = OrganizationPermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_permission_params
      params.require(:organization_permission).permit(:user_id,:organization_id,:admin)
    end
end

app/helpers/organization_permissions_helper.rb
module OrganizationPermissionsHelper
end

app/views/organization_permissions/_form.html.erb
<%= simple_form_for(@organization_permission) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%=f.input :user_id%>
    <%=f.input :organization_id%>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/organization_permissions/edit.html.erb
<h1>Editing Organization Permission</h1>

<%= render 'form', organization_permission: @organization_permission %>

<%= link_to 'Show', @organization_permission %> |
<%= link_to 'Back', organization_permissions_path %>

app/views/organization_permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Organization Permissions</h1>
<table class="table">
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @organization.each do |organization| %>
      <tr>
        <td><%=@organization.first.name%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Organization Permission', new_organization_permission_path %>
<%= link_to "back", organization_path(params[:organization_id])%>

app/views/organization_permissions/new.html.erb
<h1>New Organization Permission</h1>

<%= render 'form', organization_permission: @organization_permission %>

<%= link_to 'Back', organization_permissions_path %>

app/views/organization_permissions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_organization_permission_path(@organization_permission) %> |
<%= link_to 'Back', organization_permissions_path %>