config/routes.rb
Rails.application.routes.draw do


  #resources :organization_permissions
  resources :organizations do
    resources :properties do
      resources :bookings
    end

    resources :permissions

  end
  
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
  devise_for :users, :path  => '/users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=end
  #devise_scope :user do
  #   get   '/users/sign_in'  => 'users/sessions#new',  as: :new_user_session
  #end
  devise_for :users, path: "", controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmation: "users/confirmations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}


  resources :users

  root "static_pages#about"
  match 'about_us', to: 'static_pages#about', via: :get
  match 'team', to: 'static_pages#team', via: :get
  match 'contact_us', to: 'static_pages#contact_us', via: :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  #match '404', to:  redirect('/')

  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, :via => :all
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_one :role
  belongs_to :user
  belongs_to  :organization
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]
  
  # GET /permissions
  # GET /permissions.json
  def index
    @organization = Organization.find(params[:organization_id])
    @permissions = Permission.where(:permissible_type => "Organization", :permissible_id => @organization.id)
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @organization = Organization.find(params[:organization_id])
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        @organization=Organization.find(params[:organization_id])
        format.html { redirect_to organization_permissions_path(@organization,@permission), notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @organization= Organization.find(params[:organization_id]) 
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.fetch(:permission, {})
    end
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/permissions/_form.html.erb
<%= simple_form_for([@organization, @permission]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">

  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/permissions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Permissions</h1>

<table class="table">
  <thead>
    <tr>

      <th colspan="3">users name</th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%=permission.user.name%></td>
        <td><%= link_to 'Show', organization_permissions_path(@organization), class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_organization_permission_path(@organization, permission), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', organization_permissions_path(@organization, permission), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# link_to 'New Permission', new_organization_permission_path(@organization) %>
<%=link_to 'Back', organization_path(@organization), class: "btn"%>

app/views/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Back', organization_permission_path(@organization) %>

app/views/permissions/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>