config/routes.rb
Rails.application.routes.draw do


  #resources :organization_permissions
  resources :organizations do
    resources :properties do
      resources :bookings
    end

    resources :permissions

  end
  
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
  devise_for :users, :path  => '/users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=end
  #devise_scope :user do
  #   get   '/users/sign_in'  => 'users/sessions#new',  as: :new_user_session
  #end
  devise_for :users, path: "", controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmation: "users/confirmations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}


  resources :users

  root "static_pages#about"
  match 'about_us', to: 'static_pages#about', via: :get
  match 'team', to: 'static_pages#team', via: :get
  match 'contact_us', to: 'static_pages#contact_us', via: :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  #match '404', to:  redirect('/')

  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, :via => :all
end

app/models/organization.rb
class Organization < ApplicationRecord
  has_many :permissions
  has_many :users, through: :permissions, :source => :permissible, :source_type => "Permission"
  has_many :properties
 accepts_nested_attributes_for :users
  validates_presence_of :name

  def has_an_admin
      #errors.add(:base, 'must add at least one user') if self.organization_permissions.blank?
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: [:show, :edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @properties = @organization.properties
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        @org = Permission.create({permissible_id: @organization.id, permissible_type: "Organization" , user_id: current_user.id, role_id: 1})
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url, notice: 'Organization was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:name, :description)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
  def permissionPage
    if params[:view_type] == "Permission"
     "btn btn-info" 
    else
      "btn btn-default"
    end
  end
  def propertiesPage
    if params[:view_type] == "Properties"
     "btn btn-info" 
    else
      "btn btn-default"
    end

  end
end

app/views/organizations/_form.html.erb
<%= simple_form_for(@organization) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description%>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-success" %>
  </div>
<% end %>
<br>

app/views/organizations/_properties.html.erb
<p> test </p>

app/views/organizations/_property.html.erb
<p> test</p>

app/views/organizations/_resource.html.erb
<p> test </p>

app/views/organizations/edit.html.erb
<h1>Editing Organization</h1>

<%= render 'form', organization: @organization %>

<%= link_to 'Show', @organization %> |
<%= link_to 'Back', organizations_path %>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td class="col-md-3"><%=organization.name%></td>
        <td><%= link_to 'Show', organization, class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_organization_path(organization), class: "btn btn-warning" %></td>
        <td><%= link_to 'Destroy', organization, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Organization', new_organization_path %>

app/views/organizations/new.html.erb
<h1>New Organization</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<%= render 'form', organization: @organization %>

<%= link_to 'Back', organizations_path %>
  </div>
</div>

app/views/organizations/show.html.erb
<h1><%=@organization.name%></h1>
<p> <%= @organization.description%></p>
<%= link_to "View Permissions", organization_path(@organization, {view_type: "Permission"}), class: permissionPage%>

<%= link_to "View Properties", organization_path(@organization, {view_type: "Properties"}), class: propertiesPage%>
<% if params[:view_type] == "Permission"%>
<% else %>
   <%=render partial: "/properties/property", locals: {properties: @properties, organization: @organization}%>

<%# link_to 'Join Organization', organization_permission_path(@organization,@permission), method: :post, class: "btn btn-success"%>


<% end %>
<%# link_to "View Resources", organization_properties_path({:organization_id =>  @organization}),class: "btn btn-info"%>
<br>
<br>
<%= link_to 'Edit', edit_organization_path(@organization) %> |
<%= link_to 'Back', organizations_path %>