config/routes.rb
Rails.application.routes.draw do


  #resources :organization_permissions
  resources :organizations do
    resources :properties do
      resources :bookings
    end

    resources :permissions

  end
  
  #devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
=begin
  devise_for :users, :path  => '/users', controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
=end
  #devise_scope :user do
  #   get   '/users/sign_in'  => 'users/sessions#new',  as: :new_user_session
  #end
  devise_for :users, path: "", controllers: { sessions: "users/sessions", registrations: "users/registrations", confirmation: "users/confirmations" }, path_names: { sign_in: 'login', password: 'forgot', confirmation: 'confirm', unlock: 'unblock', sign_up: 'register', sign_out: 'signout'}


  resources :users

  root "static_pages#about"
  match 'about_us', to: 'static_pages#about', via: :get
  match 'team', to: 'static_pages#team', via: :get
  match 'contact_us', to: 'static_pages#contact_us', via: :get
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :destroy_user
  #match '404', to:  redirect('/')

  match ':status', to: 'errors#show', constraints: {status: /\d{3}/ }, :via => :all
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<nav>
		<ul>
          <li><%=link_to "About Us", about_us_path%></li>
          <li><%=link_to "The Team", team_path%></li>
          <li><%=link_to "Contact Us", contact_us_path%></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class="container">
			<%# link_to "sample app",root_path,id: "logo" %>
			<nav>
				<ul class="nav pull-right">

                  <%if user_signed_in? %>
                <li>
				<a href="#" class="dropdown-toggle" data-toggle="dropdown" id="username"><%=current_user.name%><b class="caret"></b></a>
                  <ul class="dropdown-menu">
                    <li>
                      <%=link_to "Profile", user_path(current_user) %>
                    </li>
                    <li>
                      <%=link_to "Organizations", organizations_path%>
                    </li>
                    <li>
                      <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
                    </li>
                  </ul>
                </li>

                  <% else %>
                  <li>
                    <%= link_to('Login', new_user_session_path, remote: true)  %>  
                  </li>
                  <li>
  <%# link_to "Sign Up", new_registration_path('user'), remote: true %><br />
                  </li>
                  
                  <% end %>
                </ul>
			</nav>
		</div>
	</div>

</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_modal.html.erb
<!-- modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content" id="mainModal" >
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!--IF THIS CHANGES NEED TO UPLOAD TO GIT! THIS IS IN THE GITIGNORE FILE-->
    <title><%= full_title(yield(:title)) %></title>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track'  => true %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track' =>  true %>
      <%= csrf_meta_tags %>
      <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/modal' %>
    <%= render 'layouts/header' %>
    <div class="container">
        <%= render 'layouts/messages'%>
        <div class="container-fluid">
          <%= yield %>
        </div>
        <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>